App\Entity\Format:
    attributes:
        id:
            groups: ['format-read']
        name:
            groups: ['format-read', 'format-write']
        description:
            groups: [ 'format-read', 'format-write' ]
        game:
            groups: [ 'format-read', 'format-write' ]
