App\Entity\User:
    attributes:
        id:
            groups: ['user-read']
        username:
            groups: ['user-read', 'user-write']
        address:
            groups: [ 'user-read', 'user-write' ]
        picture:
            groups: [ 'user-read', 'user-write' ]
        myFriends:
            groups: [ 'user-read', 'user-write' ]
        formats:
            groups: [ 'user-read', 'user-write' ]
        email:
            groups: [ 'user-read', 'user-write' ]
        name:
            groups: [ 'user-read', 'user-write' ]
        birthday:
            groups: [ 'user-read', 'user-write' ]
        firstName:
            groups: [ 'user-read', 'user-write' ]
        description:
            groups: [ 'user-read', 'user-write' ]
        plainPassword:
            groups: ['user-write']
