App\Entity\User:
    attributes:
        id:
            groups: ['user-read']
        username:
            groups: ['user-read', 'user-write']
        address:
            groups: [ 'user-read', 'user-write' ]
        plainPassword:
            groups: ['user-write']
