App\Entity\Format:
    attributes:
        normalization_context:
            groups: ['format-read']
            swagger_definition_name: 'read'
        denormalization_context:
            groups: ['format-write']
            swagger_definition_name: 'write'
    collectionOperations:
        get:
            filters:
                - 'format.search_filter'
        post: ~
