App\Entity\Game:
    attributes:
        normalization_context:
            groups: ['game-read']
            swagger_definition_name: 'read'
        denormalization_context:
            groups: ['game-write']
            swagger_definition_name: 'write'
    collectionOperations:
        get:
            filters:
                - 'game.search_filter'
        post: ~
