App\Entity\User:
    attributes:
        normalization_context:
            groups: ['user-read']
            swagger_definition_name: 'read'
        denormalization_context:
            groups: ['user-write']
            swagger_definition_name: 'write'
    collectionOperations:
        get:
            filters:
                - 'user.search_filter'
                - 'user.boolean_filter'
        post: ~
