App\Entity\User:
    attributes:
        order:
            name: 'ASC'
        normalization_context:
            groups: ['user-read']
            swagger_definition_name: 'read'
        denormalization_context:
            groups: ['user-write']
            swagger_definition_name: 'write'
    collectionOperations:
        get:
            filters:
                - 'user.search_filter'
        post: ~
        get_current:
            method: GET
            controller: App\Controller\GetCurrentUserAction
            path: /users/current
            openapi_context:
                summary: >
                    Retrieves current user from your connection
        get_swipe:
            method: GET
            controller: App\Controller\FindUserToSwipeAction
            path: /users/swipe
            openapi_context:
                summary: >
                    Retrieves user to swipe
