App\Entity\User:
    attributes:
        normalization_context:
            groups: ['user-read']
            swagger_definition_name: 'read'
        denormalization_context:
            groups: ['user-write']
            swagger_definition_name: 'write'
    collectionOperations:
        get:
            filters:
                - 'user.search_filter'
        post: ~
        get_current:
            method: GET
            controller: App\Controller\GetCurrentUserAction
            path: /users/current
            openapi_context:
                summary: >
                    Retrieves current user from your connection
