services:
    address.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments:
            - 'name': 'ipartial'
              'assets': 'exact'
        tags: ['api_platform.filter']
    adress.boolean_filter:
        parent: 'api_platform.doctrine.orm.boolean_filter'
        arguments:
            - 'active': ~
        tags: ['api_platform.filter']
