services:
    format.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments:
            - 'name': 'ipartial'
              'game': 'ipartial'
        tags: ['api_platform.filter']
