services:
    user.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments:
            - 'username': 'ipartial'
              'email': 'ipartial'
        tags: ['api_platform.filter']
