api_platform:
    title: Magic Tinder
    version: 1.0.0
    mapping:
        paths: 
            - '%kernel.project_dir%/config/api_platform'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            enabled: true
            items_per_page: 30
            client_items_per_page: true
            items_per_page_parameter_name: perPage
    # Mercure integration, remove if unwanted
    mercure:
        enabled: false
#        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
    # Good defaults value for REST APIs
    defaults:
        stateless: true
        # Good cache defaults
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
