vich_uploader:
    db_driver: orm
    mappings:
        media_object:
            uri_prefix: /images/media
            upload_destination: '%kernel.project_dir%/public/images/media'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    metadata:
        auto_detection: false
        directories:
            - { path: '%kernel.project_dir%/config/vich_uploader', namespace_prefix: 'App' }
